### ISSUE TITLE
List readonly system requirements

### ISSUE THREAD

**Issue by ahmetozer** [ahmetozer/nginx-basic-cdn-example#4]
System designed to work on embedded systems and may be the embedded system has read-only root file system.

- [ ] list currently used paths
- [ ] Make configurable path configuration in case of user wants to allocate state in different path or device

**Comment by ahmetozer** [comment]
```yaml
CurrentPaths:
- desc: OverlayFS chagne directory
  path: /var/lib/sandal/containers/${containerName}/changes/
- desc: Container Configuration and Status
  path: /var/lib/sandal/containers/${containerName}/config.json
- desc: SquashFs images
  path: /var/lib/sandal/containers/images/${imageName}
```
